
services:
  dfacdash_dev:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: dfacdash_dev
      POSTGRES_USER: dfacdash_dev
      POSTGRES_PASSWORD: dfacdash
    ports:
      - "0:5432"

  dfacdash_test:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: dfacdash_test
      POSTGRES_USER: dfacdash_test
      POSTGRES_PASSWORD: dfacdash
    ports:
      - "0:5433"